services:
#    application_app.example:
#        class: Application\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    application_app.admin.param_name:
        class: Application\AppBundle\Admin\ParamNameAdmin
        arguments: [~, Application\AppBundle\Entity\ParamName, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: sonata_content, label: ParamName}

    application_app.admin.param_type:
        class: Application\AppBundle\Admin\ParamTypeAdmin
        arguments: [~, Application\AppBundle\Entity\ParamType, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ParamType}
