<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\TimelineBundle\Entity;

use Sonata\TimelineBundle\Entity\Action as BaseAction;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Action extends BaseAction
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Remove actionComponents
     *
     * @param \Application\Sonata\TimelineBundle\Entity\ActionComponent $actionComponents
     */
    public function removeActionComponent(\Application\Sonata\TimelineBundle\Entity\ActionComponent $actionComponents)
    {
        $this->actionComponents->removeElement($actionComponents);
    }

    /**
     * Remove timelines
     *
     * @param \Application\Sonata\TimelineBundle\Entity\Timeline $timelines
     */
    public function removeTimeline(\Application\Sonata\TimelineBundle\Entity\Timeline $timelines)
    {
        $this->timelines->removeElement($timelines);
    }
}
